# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
    ]
